apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-stau
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-stau
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-stau
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-stau
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-stau
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mhsh-tenant/rhtap-demo-app/hacbs-test-project-stau@sha256:f66fd7e0998376635d34e86f494a3fbf610eab86afc4a743b75e244d694a0ecf
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
